-- MySQL Script generated by MySQL Workbench
-- Mon Dec  3 23:25:03 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------


-- -----------------------------------------------------
-- Table `estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estado` (
  `idestado` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idestado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cidade` (
  `idcidade` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `idestado` INT NULL,
  PRIMARY KEY (`idcidade`),
  INDEX `idestado_cidade_idx` (`idestado` ASC),
  CONSTRAINT `idestado_cidade`
    FOREIGN KEY (`idestado`)
    REFERENCES `estado` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `endereco` (
  `idendereco` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(300) NULL,
  `numero` VARCHAR(6) NULL,
  `complemento` VARCHAR(200) NULL,
  `bairro` VARCHAR(45) NULL,
  `cep` VARCHAR(9) NULL,
  `idcidade` INT NULL,
  PRIMARY KEY (`idendereco`),
  INDEX `idcidade_endereco_idx` (`idcidade` ASC),
  CONSTRAINT `idcidade_endereco`
    FOREIGN KEY (`idcidade`)
    REFERENCES `cidade` (`idcidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(350) NULL,
  `email` VARCHAR(250) NULL,
  `datanascimento` DATETIME NULL,
  `idendereco` INT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evento` (
  `idevento` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NULL,
  `data_inicio` DATETIME NULL,
  `data_fim` DATETIME NULL,
  `idresponsavel` INT NULL,
  `idendereco` INT NULL,
  `idcategoria` INT NULL,
  `precoingresso` FLOAT NULL,
  PRIMARY KEY (`idevento`),
  INDEX `idendereco_evento_idx` (`idendereco` ASC),
  INDEX `idcategoria_evento_idx` (`idcategoria` ASC),
  INDEX `idresponsavel_evento_idx` (`idresponsavel` ASC),
  CONSTRAINT `idendereco_evento`
    FOREIGN KEY (`idendereco`)
    REFERENCES `endereco` (`idendereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idcategoria_evento`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idresponsavel_evento`
    FOREIGN KEY (`idresponsavel`)
    REFERENCES `usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notificacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notificacao` (
  `idnotificacao` INT NOT NULL AUTO_INCREMENT,
  `idusuario` INT NULL,
  `texto` VARCHAR(400) NULL,
  PRIMARY KEY (`idnotificacao`),
  INDEX `idusuario_notificacao_idx` (`idusuario` ASC),
  CONSTRAINT `idusuario_notificacao`
    FOREIGN KEY (`idusuario`)
    REFERENCES `usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curtida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curtida` (
  `idcurtida` INT NOT NULL AUTO_INCREMENT,
  `idevento` INT NULL,
  `idusuario` INT NULL,
  PRIMARY KEY (`idcurtida`),
  INDEX `idevento_curtida_idx` (`idevento` ASC),
  INDEX `idusuario_curtida_idx` (`idusuario` ASC),
  CONSTRAINT `idevento_curtida`
    FOREIGN KEY (`idevento`)
    REFERENCES `evento` (`idevento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idusuario_curtida`
    FOREIGN KEY (`idusuario`)
    REFERENCES `usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `status` (
  `idstatus` INT NOT NULL AUTO_INCREMENT,
  `texto` VARCHAR(45) NULL,
  PRIMARY KEY (`idstatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `intencao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intencao` (
  `idintencao` INT NOT NULL AUTO_INCREMENT,
  `idusuario` INT NULL,
  `idevento` INT NULL,
  `idstatus` INT NULL,
  PRIMARY KEY (`idintencao`),
  INDEX `idstatus_idx` (`idstatus` ASC),
  INDEX `idevento_intencao_idx` (`idevento` ASC),
  CONSTRAINT `idstatus_intencao`
    FOREIGN KEY (`idstatus`)
    REFERENCES `status` (`idstatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idevento_intencao`
    FOREIGN KEY (`idevento`)
    REFERENCES `evento` (`idevento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idusuario_intencao`
    FOREIGN KEY (`idstatus`)
    REFERENCES `usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `estado`
-- -----------------------------------------------------
START TRANSACTION;

INSERT INTO `estado` (`idestado`, `nome`) VALUES (1, 'Paraná');
INSERT INTO `estado` (`idestado`, `nome`) VALUES (2, 'Santa Catarina');
INSERT INTO `estado` (`idestado`, `nome`) VALUES (3, 'Rio Grande do Sul');

COMMIT;


-- -----------------------------------------------------
-- Data for table `cidade`
-- -----------------------------------------------------
START TRANSACTION;

INSERT INTO `cidade` (`idcidade`, `nome`, `idestado`) VALUES (1, 'Videira', 2);
INSERT INTO `cidade` (`idcidade`, `nome`, `idestado`) VALUES (2, 'Fraiburgo', 2);
INSERT INTO `cidade` (`idcidade`, `nome`, `idestado`) VALUES (3, 'Caçador', 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `endereco`
-- -----------------------------------------------------
START TRANSACTION;

INSERT INTO `endereco` (`idendereco`, `logradouro`, `numero`, `complemento`, `bairro`, `cep`, `idcidade`) VALUES (1, 'Rua XV de Novembro', '115', NULL, 'Centro', '89560-000', 2);
INSERT INTO `endereco` (`idendereco`, `logradouro`, `numero`, `complemento`, `bairro`, `cep`, `idcidade`) VALUES (2, 'Av. Rio das Antas', '185', NULL, 'Centro', '89580-000', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `categoria`
-- -----------------------------------------------------
START TRANSACTION;

INSERT INTO `categoria` (`idcategoria`, `nome`) VALUES (1, 'Encontro');
INSERT INTO `categoria` (`idcategoria`, `nome`) VALUES (2, 'Workshop');
INSERT INTO `categoria` (`idcategoria`, `nome`) VALUES (3, 'Palestra');

COMMIT;


-- -----------------------------------------------------
-- Data for table `usuario`
-- -----------------------------------------------------
START TRANSACTION;

INSERT INTO `usuario` (`idusuario`, `nome`, `email`, `datanascimento`, `idendereco`) VALUES (1, 'Joseph Hahn', 'josephahahn@superrito.com', '1939-08-14', 1);
INSERT INTO `usuario` (`idusuario`, `nome`, `email`, `datanascimento`, `idendereco`) VALUES (2, 'Peter Brown', 'peterjbrown@einrot.com', '1939-01-31', 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `status`
-- -----------------------------------------------------
START TRANSACTION;

INSERT INTO `status` (`idstatus`, `texto`) VALUES (1, 'Irei');
INSERT INTO `status` (`idstatus`, `texto`) VALUES (2, 'Talvez irei');
INSERT INTO `status` (`idstatus`, `texto`) VALUES (3, 'Não irei');

COMMIT;

