-- MySQL Script generated by MySQL Workbench
-- Wed Dec 19 18:02:26 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------


-- -----------------------------------------------------
-- Table `estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estado` (
  `idestado` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idestado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cidade` (
  `idcidade` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `idestado` INT NULL,
  PRIMARY KEY (`idcidade`),
  INDEX `idestado_cidade_idx` (`idestado` ASC),
  CONSTRAINT `idestado_cidade`
    FOREIGN KEY (`idestado`)
    REFERENCES `estado` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `endereco` (
  `idendereco` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(200) NULL,
  `numero` VARCHAR(8) NULL,
  `bairro` VARCHAR(50) NULL,
  `cep` VARCHAR(9) NULL,
  `idcidade` INT NULL,
  PRIMARY KEY (`idendereco`),
  INDEX `idcidade_endereco_idx` (`idcidade` ASC),
  CONSTRAINT `idcidade_endereco`
    FOREIGN KEY (`idcidade`)
    REFERENCES `cidade` (`idcidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tipo_usuario` (
  `idtipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idtipo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NULL,
  `cpf` VARCHAR(13) NULL,
  `telefone` VARCHAR(11) NULL,
  `senha` VARCHAR(150) NULL,
  `datanascimento` DATE NULL,
  `idendereco` INT NULL,
  `idtipo` INT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `idendereco_usuario_idx` (`idendereco` ASC),
  INDEX `idtipousuario_usuario_idx` (`idtipo` ASC),
  CONSTRAINT `idendereco_usuario`
    FOREIGN KEY (`idendereco`)
    REFERENCES `endereco` (`idendereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idtipousuario_usuario`
    FOREIGN KEY (`idtipo`)
    REFERENCES `tipo_usuario` (`idtipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `montadora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `montadora` (
  `idmontadora` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idmontadora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo` (
  `idmodelo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `idmontadora` INT NULL,
  PRIMARY KEY (`idmodelo`),
  INDEX `idmontadora_modelo_idx` (`idmontadora` ASC),
  CONSTRAINT `idmontadora_modelo`
    FOREIGN KEY (`idmontadora`)
    REFERENCES `montadora` (`idmontadora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carro` (
  `idcarro` INT NOT NULL AUTO_INCREMENT,
  `idmodelo` INT NULL,
  `idusuario` INT NULL,
  `ano` YEAR NULL,
  `placa` VARCHAR(7) NULL,
  `chassi` VARCHAR(17) NULL,
  PRIMARY KEY (`idcarro`),
  INDEX `idusuario_carro_idx` (`idusuario` ASC),
  INDEX `idmodelo_carro_idx` (`idmodelo` ASC),
  CONSTRAINT `idmodelo_carro`
    FOREIGN KEY (`idmodelo`)
    REFERENCES `modelo` (`idmodelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idusuario_carro`
    FOREIGN KEY (`idusuario`)
    REFERENCES `usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formapagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formapagamento` (
  `idformapagamento` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idformapagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `corrida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `corrida` (
  `idcorrida` INT NOT NULL AUTO_INCREMENT,
  `idusario_motorista` INT NULL,
  `idusuario_passageiro` INT NULL,
  `data` DATETIME NULL,
  `hora_inicio` TIME NULL,
  `hora_termino` TIME NULL,
  `valor` FLOAT NULL,
  `idformapagamento` INT NULL,
  PRIMARY KEY (`idcorrida`),
  INDEX `idusuario_motorista_corrida_idx` (`idusario_motorista` ASC),
  INDEX `idusuario_passageiro_corrida_idx` (`idusuario_passageiro` ASC),
  INDEX `idformapagamento_corrida_idx` (`idformapagamento` ASC),
  CONSTRAINT `idusuario_motorista_corrida`
    FOREIGN KEY (`idusario_motorista`)
    REFERENCES `usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idusuario_passageiro_corrida`
    FOREIGN KEY (`idusuario_passageiro`)
    REFERENCES `usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idformapagamento_corrida`
    FOREIGN KEY (`idformapagamento`)
    REFERENCES `formapagamento` (`idformapagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `tipo_usuario`
-- -----------------------------------------------------
START TRANSACTION;

INSERT INTO `tipo_usuario` (`idtipo_usuario`, `nome`) VALUES (1, 'Motorista');
INSERT INTO `tipo_usuario` (`idtipo_usuario`, `nome`) VALUES (2, 'Passageiro');

COMMIT;


-- -----------------------------------------------------
-- Data for table `formapagamento`
-- -----------------------------------------------------
START TRANSACTION;

INSERT INTO `formapagamento` (`idformapagamento`, `nome`) VALUES (1, 'Cartão de crédito');
INSERT INTO `formapagamento` (`idformapagamento`, `nome`) VALUES (2, 'Cartão de débito');
INSERT INTO `formapagamento` (`idformapagamento`, `nome`) VALUES (3, 'Dinheiro');

COMMIT;

